# This function showcases how one might write a function to be used as an
# RStudio project template. This function will be called when the user invokes
# the New Project wizard using the project template defined in the template file
# at:
#
#   inst/rstudio/templates/project/hello_world.dcf
#
# The function itself just echos its inputs and outputs to a file called INDEX,
# which is then opened by RStudio when the new project is opened.
start_project <- function(path, ...) {

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)


  # generate header
  header <- c(
    "# This file was generated by a call to 'ptexamples::hello_world()'.",
    "# The following inputs were received:",
    ""
  )

  # Create subdirectories
  subdirs <- c("R", "data", "outputs")
  lapply(subdirs, function(d) dir.create(file.path(path, d), showWarnings = FALSE))

  # Paths to package scripts and data
  script_files <- system.file("scripts", package = "appliedepi")
  data_files <- system.file("data", package = "appliedepi")

  # Copy scripts and data to the project directory
  if (file.exists(script_files)) file.copy(script_files, file.path(path, "R"), recursive = TRUE)
  if (file.exists(data_files)) file.copy(data_files, file.path(path, "data"), recursive = TRUE)


  # collect inputs
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "INDEX"))

}
